// <auto-generated />
namespace Ws_BancoTabajara.Infra.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dfoasfkodasofefaew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfoasfkodasofefaew));
        
        string IMigrationMetadata.Id
        {
            get { return "201807301743491_dfoasfkodasofefaew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
